// packages/solid/src/use-property.ts
import { Property } from '@frp-ts/core'
import { createSignal, onCleanup, Accessor } from 'solid-js'

export const useProperty = <A>(property: Property<A>): Accessor<A> => {
	const [get, set] = createSignal<A>(property.get())

	const subscription = property.subscribe({
		next: () => set(property.get),
	})

	onCleanup(() => subscription.unsubscribe())

	return get
}

// packages/react/src/use-property.ts
import { Property } from '@frp-ts/core'
import { useState, useEffect } from 'react'

export const useProperty = <A>(property: Property<A>): A => {
	const [value, setValue] = useState(property.get())
	useEffect(() => {
		const subscription = property.subscribe({
			next: () => setValue(() => property.get()),
		})
		return subscription.unsubscribe
	}, [])
	return value
}
